import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Seller1',
        logo: '/images/logo.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Seller2',
      email: 'seller@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Seller2',
        logo: '/images/logo2.png',
        description: 'top seller',
        rating: 5,
        numReviews: 20,
      },

    },
  ],
  products: [
    {
      name: 'Nike Slim T-shirt',
      category: 'T-shirts',
      image: '/images/p1.jpg',
      price: 20,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 101,
      description: 'Slim Fit T-shirt'
    },
    {
      name: 'Adidas Long Sleeve Shirt',
      category: 'Long Sleeve Shirts',
      image: '/images/p2.jpg',
      price: 19,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 120,
      description: 'Long sleeve',
    },
    {
      name: 'Polo Shirt',
      category: 'Polo Shirts',
      image: '/images/p3.jpg',
      price: 60,
      countInStock: 0,
      brand: 'Polo',
      rating: 4.8,
      numReviews: 17,
      description: 'High Quality Polo Shirt',
    },
    {
      name: 'Nike Soccer Ball',
      category: 'Balls',
      image: '/images/p4.jpg',
      price: 150,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 14,
      description: 'Fifa Quality Ball',
    },
    {
      name: 'Adidas Tennis Shoes',
      category: 'Tennis Shoes',
      image: '/images/p5.jpg',
      price: 165,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Apple Ipad',
      category: 'Tablets',
      image: '/images/p6.jpg',
      price: 199,
      countInStock: 122,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 152,
      description: 'high quality tablet',
    },
  ],
};
export default data;
